name: ndash
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.26.0-17.5.pre"

dependencies:
  file: ">=6.0.0-0 <7.0.0"
  flutter:
    sdk: flutter
  http: ">=0.13.0-0 <0.15.0"
  dio: ^5.2.0+1
  http_parser: ^4.0.2
  path_provider: ^2.0.15
  shared_preferences: '>=2.0.0 <3.0.0'
  battery_info: ^1.1.1
  carrier_info: ^2.0.8
  permission_handler: ^10.4.3
  device_info_plus: ^8.2.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  fake_async: any
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  test: ^1.16.0-nullsafety
  transparent_image: ^2.0.1

dependency_overrides:
  # for in_app_picture_in_picture
  wakelock: ^0.6.2

flutter:
  assets:
    - packages/ndash/assets/images/pen.png

  plugin:
    platforms:
      android:
        default_package: ndash
      ios:
        default_package: ndash
      linux:
        default_package: ndash
      macos:
        default_package: ndash
      web:
        default_package: ndash

  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Regular.ttf
    - family: ndash-icons
      fonts:
        - asset: lib/assets/fonts/Ndash-Icons.ttf

