name: ndash
description: A new Flutter package project.

publish_to: none

version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.26.0-17.5.pre"

dependencies:
  file: "^7.0.0"
  flutter:
    sdk: flutter
  battery_plus: ^6.1.0
  dio: ^5.2.0+1
  http: "^1.2.1"
  http_parser: ^4.0.2
  device_info_plus: ^10.1.0
  path_provider: ^2.0.15
  # override the fun onDetachedFromActivityForConfigChanges() to suppress the warning from playstore
  # https://pub.dev/packages/sim_card_info to check for releases periodically to see if the 
  # author includes a change to fix this in their package, then we will stop maintaining our fork.
  sim_card_info:
    git:
      url: https://github.com/harshgtet/sim_card_info
      ref: detach_update
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  change_app_package_name: ^1.1.0
  fake_async: any
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  test: ^1.16.0-nullsafety
  transparent_image: ^2.0.1

flutter:
  assets:
    - packages/ndash/assets/images/pen.png


  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Regular.ttf
    - family: ndash-icons
      fonts:
        - asset: lib/assets/fonts/Ndash-Icons.ttf

