name: ndash
description: A new Flutter package project.

publish_to: none

version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.3 <4.0.0"

dependencies:
  battery_plus: ^7.0.0
  carrier_info: ^3.0.3
  device_info_plus: ^12.1.0
  dio: ^5.9.0
  file: ^7.0.1
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  change_app_package_name: ^1.5.0
  fake_async: any
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  test: ^1.16.0-nullsafety
  transparent_image: ^2.0.1

dependency_overrides:
  wakelock_plus: ^1.4.0

flutter:
  assets:
    - packages/ndash/assets/images/pen.png

  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Regular.ttf
    - family: ndash-icons
      fonts:
        - asset: lib/assets/fonts/Ndash-Icons.ttf

