name: ndash
description: A new Flutter package project.
repository: https://github.com/BunnyMan1/nconnect_feedback/
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.13.4

dependencies:
  battery_plus: ^7.1.1
  carrier_info_plus: ^2.0.1
  device_info_plus: ^13.2.0
  dio: ^5.11.1
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/ndash/assets/images/pen.png

  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Regular.ttf
    - family: ndash-icons
      fonts:
        - asset: lib/assets/fonts/Ndash-Icons.ttf
